### ISSUE TITLE
[Fedora29] No audio source

### ISSUE THREAD

**Issue by ForlornWongraven** [yucefsourani/sgvrecord#1]
I installed sgvrecord via the copr repo on Fedora 29 as documented. I cannot select an audio source for my videos though.

**Comment by yucefsourani** [comment]
What is the output of this commands?
aplay -l

and

pactl list | grep -A3 'Source #'

Thanks You .

**Comment by ForlornWongraven** [comment]
aplay -l
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: PCH [HDA Intel PCH], Gerät 0: ALC1150 Analog [ALC1150 Analog]
  Sub-Geräte: 0/1
  Sub-Gerät #0: subdevice #0
Karte 0: PCH [HDA Intel PCH], Gerät 1: ALC1150 Digital [ALC1150 Digital]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 3: HDMI 0 [HDMI 0]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 7: HDMI 1 [HDMI 1]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 8: HDMI 2 [HDMI 2]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 9: HDMI 3 [HDMI 3]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 10: HDMI 4 [HDMI 4]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: HDMI [HDA ATI HDMI], Gerät 11: HDMI 5 [HDMI 5]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

pactl list | grep -A3 'Quelle #'
Quelle #0
	Status: RUNNING
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Beschreibung: Monitor of Internes Audio Analog Stereo
--
Quelle #1
	Status: RUNNING
	Name: alsa_input.pci-0000_00_1f.3.analog-stereo
	Beschreibung: Internes Audio Analog Stereo

I had to change 'Source' to 'Quelle' which is the german word for source.

**Comment by ForlornWongraven** [comment]
Ah, perfect. Working now as intended.
